# Configuração do SonarCloud
sonar.projectKey=TecnologiaIntegrada_apijogoimobiliario
sonar.organization=canada-software-com

# Informações do projeto
sonar.projectName=API Jogo Imobiliário
sonar.projectVersion=1.0.0

# Código fonte
sonar.sources=app
sonar.tests=tests

# Python específico
sonar.python.version=3.11

# Cobertura de código
sonar.python.coverage.reportPaths=coverage.xml

# Exclusões
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/venv/**,**/env/**,**/tests/**

# Encoding
sonar.sourceEncoding=UTF-8