# Configuração do SonarCloud
sonar.projectKey=TecnologiaIntegrada_apijogoimobiliario

# Informações do projeto
sonar.projectName=API Jogo Imobiliário
sonar.projectVersion=1.0.0

# Código fonte
sonar.sources=app
sonar.tests=tests

# Python específico
sonar.python.version=3.11

# Exclusões
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/venv/**,**/env/**,**/tests/**

# Encoding
sonar.sourceEncoding=UTF-8
