sonar.projectKey=TecnologiaIntegrada_apijogoimobiliario
sonar.organization=tecnologiaintegrada
sonar.projectName=API Jogo Imobiliário
sonar.projectVersion=1.0.0
sonar.sources=app
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
